# This is the name of the workflow that will be displayed in the Actions tab
name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Container
        run: echo "Docker Container built"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the app
        run: echo "Docker Compose deployed the app"
