# This is a comment
name: Hello
#run on an automatic trigger, whenver change is pushed to branch deployment
on:
 push:
  branches: [main]

  paths:
   -'**.html'
    

# These are jobs inside the workflow
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "Hello Dosto"

      - name: Say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name:  verson of python, docker,etc
        run: docker --version && python --version
